package h17jb3.tu5.Exceptions;
//KHỐI TRY/CATCH

import java.io.IOException;

public class TryCatchExample {
	public static void main(String[] args) {
		// try {
		// methodeX();
		// System.out.println("Cau lenh ngay sau methodX()");
		// } catch (NullPointerException e) {
		// System.out.println("Co loi trong khoi try");
		// }
		// System.out.println("Cau lenh sau try/catch");
		// }

		// try {
		// A();
		// } catch (Exception e) {
		// System.out.println("Co loi trong A()");
		// }

		// try {
		// x = System.in.read();
		// System.out.println("x = " + x);
		// } catch (IOException e) {
		// System.out.println("Error: " + e.getMessage());
		// }

		// KHỐI TRY/ NHIỀU CATCH
		// try {
		// String s = buff.readLine();
		// int a = Integer.parseInt(s);
		// x[i++] = a;
		// } catch (IOException e) {
		// System.out.println("Error IO: " + e.getMessage());
		// } catch (NumberFormatException e) {
		// System.out.println("Error Format: " + e.getMessage());
		// } catch (ArrayIndexOutOfBoundsException e) {
		// System.out.println("Error Index: " + e.getMessage());
		// }

		// KHỐI FINALLY
		// try {
		// doSomething(); // phương thức này có thể gây ra ngoại lệ
		// } finally {
		// cleanup();
		// }

	}
}
